name: fairseq-image-captioning
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - pytorch=1.3
  - cudatoolkit=10.1
  - torchvision=0.4
  - pandas=0.25.1
  - scipy=1.3.1
  - tqdm=4.36
  - matplotlib=3.1.2
  - scikit-image=0.16.2
  - pip
  - pip:
      - fairseq==0.9.0
      - sacremoses==0.0.35
      - subword-nmt==0.3.6
